### ISSUE TITLE
Keep the old round result till the new one is over

### ISSUE THREAD

**Issue by s-soroosh** [soallpeach/onboarding#15]
On every new round, the table stops showing the previous result. so that for a few minutes the table is not complete.

**Comment by the-dr-lazy** [comment]
It can cause ambiguity about the results.
We can disambiguate it by adding a mark which indicates that it's the last result.

**Comment by s-soroosh** [comment]
How ambiguity can happen? 
We'll show the new result (full table update) just once all the tests are done, in the other word, the table is showing the previous result of all participants in the meanwhile that SoAllPeach is evaluating the new round.

**Comment by the-dr-lazy** [comment]
Let's imagine I did some change on a challenge. How can I find out the result is last or the new one before the job ends?

**Comment by s-soroosh** [comment]
As long as the job is running everybody just see the old results. 
Once it's done the table gets updated and the update time label at the top of the table updates too.

**Comment by s-soroosh** [comment]
Resolved
