### ISSUE TITLE
Test time in Action is misleading

### ISSUE THREAD

**Issue by mosajjal** [soallpeach/onboarding#23]
Hi,

I've done a bunch of tests and it looks like the time elapsed in run.py does not represent the real time of the algorithm.

I've built a couple of the contestant's containers and tested the results locally and it doesn't match up with the repo's Action results. This is what I ran:

``` perf stat docker run -it --rm -v /tmp/ch1/input.txt:/input.txt prime:CONTENSTANT /input.txt > /dev/null ```

Please let me know if you need me to share more info

**Comment by s-soroosh** [comment]
what if you write to a file rather than `/dev/null`? 
please share your numbers here, and note that Github action machine is different from your machine that can have Impact in the duration.

**Comment by mosajjal** [comment]
here's the script that I ran:

https://hastebin.com/lidadeyilo.sql

**Comment by liamplm** [comment]
I think we really should think of a better execution runtime test

I compare numbers of participants runtime with their previous result and they are very different from time to time

Even after testing my own code vs other contesters (both code on my computer), the results are pretty much different with the result on the website ... some of theme are much faster and some not

I wrote a code with the **prespecified** result (no special processing) and after the test, the result of my code was even worse compare to the normal time !!!

**Comment by the-dr-lazy** [comment]
Looks like there is an impact from Docker in the elapsed time!

#### [Docker - Dynamic job, Benchmark step](https://github.com/thebrodmann/soallpeach/runs/584581502?check_suite_focus=true)
![Screen Shot 2020-04-14 at 9 43 05 AM](https://user-images.githubusercontent.com/20781126/79188558-9451a800-7e34-11ea-9208-29cf31e63a24.png)

#### [Nix job, Benchmark step](https://github.com/thebrodmann/soallpeach/runs/584581473?check_suite_focus=true)
![Screen Shot 2020-04-14 at 9 42 51 AM](https://user-images.githubusercontent.com/20781126/79188560-961b6b80-7e34-11ea-986f-3557e9756c99.png)

**Comment by s-soroosh** [comment]
Yes, ofc docker container has an impact on the result, and picking the right docker image can contribute to reducing the overall time.

**Comment by liamplm** [comment]
> Yes, ofc docker container has an impact on the result, and picking the right docker image can contribute to reducing the overall time.

I wrote a script that measures container execution time only (and not the creation time), by `State.StartedAt` and `State.FinishedAt` from `docker inspect <container-name>` i will make a pull request for implementing that later
