### ISSUE TITLE
More accurate tests for Prime

### ISSUE THREAD

**Issue by omid** [soallpeach/onboarding#26]
I would suggest having composite numbers in the input.txt file.

Also for the output, it's better to have a reference to the input number.
Currently, you only rely on the order of numbers which doesn't seem safe! In another word, what if I accidentally print "1" as the result of 11 instead of "1" as the result of 13? The final result is correct, but you cannot see the mistake!

**Comment by s-soroosh** [comment]
Right, will add more inputs to cover more cases.

And regarding the latter point, I haven’t got how that might happen yet! For every line in input we expect a corresponding result on output.
If program returns correct answer for all cases, we don’t really need to care And verify whether the algorithm is right or not.

**Comment by omid** [comment]
In another case, in the _parallel_ or _concurrent_ worlds, the order of the resulted numbers can be different, but the result is correct.

For the input of "2, 4" you should get "1, 0" or "0, 1" and it doesn't mean it's wrong! But by having a reference back to the input, you can be sure, "2: 1, 4: 0" or "4: 0, 2: 1", both are correct.

Another case is that, imagine I just print 1055120 times "1\n", it'll be super fast and correct.

**Comment by s-soroosh** [comment]
Well, that's exactly the point! If a programmer rather writes concurrent code, should think of the synchronization on the result as well since the order matters here. In this challenge order is important and the programmer should take care of it.

**Comment by omid** [comment]
OK, understood :)

**Comment by s-soroosh** [comment]
I'll add a few false case and some outlier to the input as well, to cover more cases.
