### ISSUE TITLE
weird results 

### ISSUE THREAD

**Issue by Dawoodkhorsandi** [soallpeach/onboarding#49]
Hi

I have changed my code slightly in the last round, this is the time recorded in my machine
```
python3 original.py   10.34s user 1.98s system 99% cpu 12.340 total
python3 original.py   10.11s user 2.25s system 99% cpu 12.360 total
python3 original.py   10.35s user 2.12s system 99% cpu 12.475 total
python3 prime_checker.py   5.75s user 0.42s system 93% cpu 6.591 total
python3 prime_checker.py   5.77s user 0.39s system 93% cpu 6.572 total
python3 prime_checker.py   5.79s user 0.43s system 93% cpu 6.649 total
```

so based on those my code should work faster but the result was the opposite!

last round time 4.xx seconds
this round 160.xx seconds ://

it's so weird

**Comment by s-soroosh** [comment]
Please run docker container, to have the env as close as possible to what SoAllPeach has

**Comment by Dawoodkhorsandi** [comment]
Because of this issue, I know a little docker now. Achievement unlocked 😎. it's time to write docker in my resume 😂😂

docker based tests:
```
docker run -v ~/Desktop/input.txt:/app/input.txt -it --rm original:v1 input.txt  1.44s user 2.81s system 40% cpu 10.546 total
docker run -v ~/Desktop/input.txt:/app/input.txt -it --rm string_concatenation:v1 input.txt  0.05s user 0.06s system 0% cpu 3:42.01 total
docker run -v ~/Desktop/input.txt:/app/input.txt -it --rm list_join:v1 input.txt  0.05s user 0.03s system 1% cpu 6.643 total

```

That minor change in my code was removing print in for loop and using string concatenation instead which it turned out to be much slower [(approximately 30-100 times slower) ](https://bitbucket.org/pypy/pypy/issues/1925/very-slow-string-concatenation) in pypy than CPython running in my local machine 

surprised of last round as you see the list_join container are faster than the original one(print in for loop), but the GitHub actions show opposite results 😐

Thank you for soallpeaching us:)

**Comment by s-soroosh** [comment]
You're welcome Dawood, hope this project would be useful for you ;)
