### ISSUE TITLE
Test files

### ISSUE THREAD

**Issue by Mj80Sh** [soallpeach/onboarding#59]
Hi.

First of all, I have to thank you for your amazing idea.

As we see , in test file we have 5 non-prim numbers at first, and another numbers are prim!!!
So I can just print 0 for first 5 records and 1 for other records!!!!

As a result, I don't think test files are fair.
I think it's better that have more non-prim numbers in random places.
It can bring us closer to reality.

**Comment by the-dr-lazy** [comment]
Somehow related to #26

**Comment by s-soroosh** [comment]
As the input and the expected result are open. one can simply just return the `expected.txt` file without any computation at all. 

Hopefully, people would like to challenge themselves rather than just getting rank on the table. 
But let's see :)

**Comment by Mj80Sh** [comment]
It may be interesting that one of my friends did this, but he still couldn't set the best record! :))))
