### ISSUE TITLE
Don't overwrite CMD directives

### ISSUE THREAD

**Issue by Rmaan** [soallpeach/onboarding#64]
If your Docker file has a CMD directive instead of ENTRYPOINT it won't work with current way of running. We basically overwrite any CMD directive so if somebody has both we will also break that.

Sample:
https://soallpeach.run/scores/3009
https://github.com/nnourani/soallpeach/blob/master/prime/Dockerfile

**Comment by s-soroosh** [comment]
Those cases hadn’t worked with previous way of running either, right?

It’s mentioned that we pass the filename as argument (command) to the container. So CMD is overriden by definition.

**Comment by Rmaan** [comment]
I thought in array form docker run parameters will be appended to CMD but I was wrong 😅it's only for ENTRYPOINT in array form.
